[project]
name = "desktop-streamer"
version = "1.0.0"
requires-python = "==3.14.*"
dependencies = [
    "ipykernel==7.3.0",
    "numpy==2.5.2",
    "pandas==3.0.5",
    "matplotlib==3.11.1",
    "seaborn==0.13.2",
    "torch==2.13.0",
    "torchaudio==2.11.0",
    "pillow==12.3.0",
    "onnx>=1.22.0",
    "onnxruntime>=1.29.0",
    "fastapi[standard]>=0.141.1",
]
[[tool.uv.index]]
name = "pytorch-cu132"
url = "https://download.pytorch.org/whl/cu132"
explicit = true
